# Generated by Django 6.0.2 on 2026-03-28 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hod', 'HOD'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('email_notifications', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(blank=True, help_text='Broadcast to all users of this role', max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.userprofile')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Other', max_length=50)),
                ('default_branch', models.CharField(blank=True, max_length=100)),
                ('expected_attendees', models.PositiveIntegerField(default=100)),
                ('frequency', models.CharField(choices=[('yearly', 'Yearly'), ('semesterly', 'Every Semester'), ('monthly', 'Monthly'), ('one_time', 'One Time')], default='yearly', max_length=20)),
                ('typical_month', models.PositiveSmallIntegerField(blank=True, help_text='1-12 for typical scheduling month', null=True)),
                ('typical_duration_days', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
                ('default_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.venue')),
            ],
            options={
                'db_table': 'event_templates',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('branch', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Other', 'Other')], default='Other', max_length=50)),
                ('expected_attendees', models.PositiveIntegerField(default=100)),
                ('admin_note', models.TextField(blank=True)),
                ('suggested_date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('public_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('public_description', models.TextField(blank=True, help_text='Extra info shown on public page')),
                ('registration_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventtemplate')),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_events', to='core.userprofile')),
                ('suggested_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_events', to='core.venue')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.venue')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CollegeCalendarEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Examination'), ('semester_start', 'Semester Start'), ('semester_end', 'Semester End'), ('vacation', 'Vacation'), ('event', 'College Event'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_recurring_yearly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
            ],
            options={
                'verbose_name_plural': 'College Calendar Entries',
                'db_table': 'college_calendar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CoordinatorRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coord_requests', to='core.event')),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coord_approvals', to='core.userprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coord_requests', to='core.userprofile')),
            ],
            options={
                'db_table': 'coordinator_requests',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'event')},
            },
        ),
    ]
